services:
  mongodb:
    build: ./mongodb
    image: navomika18/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db  #/data/db is container path refering to host path 
  catalogue:
     build: ./catalogue
     image: navomika18/catalogue:v1
     container_name: catalogue
     depends_on:
     - mongodb
  redis:
     image: redis:latest
     container_name: redis
     volumes:
     - redis:/data
  mysql:
      build: ./mysql
      image: navomika18/mysql:v1
      container_name: mysql
      volumes:
      - mysql:/var/lib/mysql
  rabbitmq:
       image: rabbitmq:3
       container_name: rabbitmq
       environment: 
         RABBITMQ_DEFAULT_USER: roboshop
         RABBITMQ_DEFAULT_PASS: roboshop123
       volumes: # -v rabbitmq:/var/lib/rabbitmq
       - rabbitmq:/var/lib/rabbitmq
  user:
       build: ./user
       image: navomika18/user:v1
       container_name: user
       depends_on:
       - mongodb
       - redis
  cart:
        build: ./cart
        image: navomika18/cart:v1
        container_name: cart
        depends_on:
        - redis
        - catalogue
  shipping:
        build: ./shipping
        image: navomika18/shipping:v1
        container_name: shipping
        depends_on:
        - mysql
        - cart
  payment:
        build: ./payment
        image: navomika18/payment:v1
        container_name: payment
        depends_on:
        - rabbitmq
        - cart
        - user
  frontend:
        build: ./frontend
        image: navomika18/frontend:v1
        container_name: frontend
        ports:
        - "80:80"
        depends_on:
        - catalogue
        - user
        - cart
        - payment
        - shipping
networks: 
  defaults:
    driver: bridge
    name: roboshop
    external: false #true if you have created a network manually using the docker network command

volumes:
  mongodb: #/var/lib/docker/volumes   host path 
  mysql:
  redis:
  rabbitmq:
